### PR TITLE
Move (de-)serialization from Newtonsoft.JSON to System.Json.Text

### PR DESCRIPTION
**Pull request by vader1986**
https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/issues/63

### CODE REVIEW

**Comment by vader1986** [comment]
I can't really get the unit tests running on my machine (yet). However, the sample services are running - is there anything in particular to look for?

**Comment by vader1986** [comment]
Unit tests are running through fine now (just had my cluster running in a different namespace & selected wrong k8s config)

**Comment by SamEmber** [comment]
Thanks @vader1986, @galvesribeiro would you be able to take a look when possible please? Thanks!

**Comment by galvesribeiro** [comment]
Hey folks. I tried to run the test here but it doesn't work. In the past it used to work just fine. @vader1986 what have you don't to make it work? I keep getting 404 on all requests. I wonder if the APIs changed.

**Review by galvesribeiro — APPROVED** [review]
LGTM. Thank you!

**Comment by galvesribeiro** [comment]
I've fixed the tests. Thank you!

**Pull request merged**
