### PR TITLE
Upgrade projects to dotnet8

### PR DESCRIPTION
**Pull request by vader1986**
Closes: #70

### CODE REVIEW

**Comment by galvesribeiro** [comment]
Thanks @vader1986!

**Review by galvesribeiro — APPROVED** [review]
LGTM

**Comment by turowicz** [comment]
you didnt update the package references that still point to 7.x @vader1986 @galvesribeiro

**Comment by vader1986** [comment]
My understanding was that Orleans 8 is not released yet (only a rc). I can add another PR to upgrade other packages (`Microsoft.Extensions.*`) if you like?

**Comment by turowicz** [comment]
You can either upgrade them to 8.0-rc1 or you could just mark them as private assets so nuget doesnt install them automatically.

image

**Comment by vader1986** [comment]
> You can either upgrade them to 8.0-rc1 or you could just mark them as private assets so nuget doesnt install them automatically and they don't appear as dependencies.
> 
> image

#72

**Pull request merged**
