### PR TITLE
Upgrade Orleans to 3.5.1 and Kubernetes client to match

### LINKED ISSUE #55: Fix: Orleans.Hosting.KubernetesHosting: System.MissingMethodException
Multiple Kubernetes client updates have changed the method signatures and when using a newer version of the client (e.g. when using [KubeOps](https://github.com/buehler/dotnet-operator-sdk/) in conjunction with Orleans in the same app) the following error is thrown:

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Object> k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(k8s.IKubernetes, System.Object, System.String, System.String, System.String, System.String, System.String, System.Threading.CancellationToken)'.
    at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at Orleans.Clustering.Kubernetes.KubeMembershipTable.TryInitClusterVersion()
    at Orleans.Clustering.Kubernetes.KubeMembershipTable.InitializeMembershipTable(Boolean tryInitTableVersion)
    at Orleans.Runtime.MembershipService.MembershipTableManager.Start()
```

The fix is to upgrade the Kubernetes C# SDK to the latest version, and I have a PR in with the Orleans repo (https://github.com/dotnet/orleans/pull/7346) to do that as well as a PR ready for this repo once I see the disposition of their fix timing but both `Orleans.Hosting.Kubernetes` and `Orleans.Clustering.Kubernetes` should to be upgraded to match versions and move in lockstep so one doesn't drag the other down into an incompatible state.

### PR DESCRIPTION
**Pull request by highlyunavailable**
This PR upgrades the Orleans core dependencies and the Kubernetes client to match, as well as adding multi-targeting (to match Orleans itself again).

Fixes #55

### CODE REVIEW

**Comment by Zoney** [comment]
Great work!

**Comment by runenilsenoe** [comment]
Nice🎉

**Comment by dpiessens** [comment]
@Gutemberg Ribeiro Can you or one of the maintainers approve this? I think the outdated version may be contributing to issues we're seeing.

**Comment by cdemi** [comment]
Is there anything we can do to merge this issue? We'd rather use the official NuGet but since it's not merged we have to fork and build our own

**Review by galvesribeiro — APPROVED** [review]
LGTM thanks!

**Pull request merged**
