### PR TITLE
Removed unused dependencies

### PR DESCRIPTION
**Pull request by xontab**
* Removed unused package dependency to increase compatibility

### CODE REVIEW

**Comment by galvesribeiro** [comment]
Thanks!

**Comment by xontab** [comment]
Can you please push the new NuGet package?

**Comment by xontab** [comment]
Can you please push the new NuGet package @galvesribeiro?

**Comment by xontab** [comment]
Gentle reminder @galvesribeiro ... Can you please push it to NuGet.org?

**Comment by galvesribeiro** [comment]
Hey @xontab sorry!

I completely forgot the notification on this issue. Just pushed the package to NuGet.

Thanks for the contribution.

**Comment by xontab** [comment]
No worries ... Thanks a lot

**Pull request merged**
