### PR TITLE
Upgrade Orleans dependencies to 8.0.0

### PR DESCRIPTION
**Pull request by vader1986**
https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/issues/73

### CODE REVIEW

**Review by insylogo — APPROVED** [review]
pretty cut and dry - I wonder if there's anyone out there who can merge?

**Comment by ReubenBond** [comment]
cc @galvesribeiro

**Review by galvesribeiro — APPROVED** [review]
LGTM

**Comment by galvesribeiro** [comment]
Sorry, I've missed the PR notification originally. Merging now. Release soon.

Thanks!

**Pull request merged**
